"""
Generate n bits data.
"""

from secrets import randbits
import math
from typing import Optional

from diffusion_hash_inv.config import MessageConfig, HashConfig
from diffusion_hash_inv.main import RuntimeConfig
from diffusion_hash_inv.logger import Logs
from diffusion_hash_inv.utils import FileIO

class NBitsGenerator:
    """
    Generate n bits data.
    """

    def __init__(self, runtime_config: RuntimeConfig,
                io_controller: FileIO, program_start_time:str) -> None:
        self.runtime_config = runtime_config
        self.msg_cfg: MessageConfig = runtime_config.message
        self.hash_cfg: HashConfig = runtime_config.hash

        self.io_controller = io_controller

        self.gen_start_time = program_start_time

    @staticmethod
    def bytes_to_hex_block(b: bytes, *, word_bytes: int = 2, line_bytes: int = 16,
                    pad_last: bool = True) -> str:
        """
        Convert bytes to a formatted hexadecimal string.
        """
        out_lines = []
        for i in range(0, len(b), line_bytes):
            line = b[i:i+line_bytes]
            groups = []
            for j in range(0, len(line), word_bytes):
                chunk = line[j:j+word_bytes]
                hs = chunk.hex()
                if pad_last and len(chunk) < word_bytes:
                    hs = hs.zfill(word_bytes * 2)  # 마지막 덜 찬 그룹 0패딩
                groups.append(hs)
            out_lines.append(' '.join(groups))
        return '\n'.join(out_lines)

    @staticmethod
    def print_hex(msg, x):
        """
        Print the hexadecimal representation of the given bytes.
        """
        if msg.endswith("\n"):
            print(msg, end="")
        else:
            print(msg+":")
        print(NBitsGenerator.bytes_to_hex_block(x))
        print()

    @staticmethod
    def print_bin(msg, data):
        """
        Print the binary representation of the given integer.
        """
        if msg.endswith("\n"):
            print(msg, end="")
        else:
            print(msg+":")
        print(' '.join(f'{x:08b}' for x in data))
        print()

    @staticmethod
    def print_bin_in_big_endian(msg, data, endian='little'):
        """
        Print the binary representation of the given integer.
        """
        if endian == 'big':
            NBitsGenerator.print_bin(msg, data)
        else:
            NBitsGenerator.print_bin(msg + " (Big Endian)", data[::-1])

    @staticmethod
    def print_hex_in_big_endian(msg, data, endian='little'):
        """
        Print the hexadecimal representation of the given bytes.
        """
        if endian == 'big':
            NBitsGenerator.print_hex(msg, data)
        else:
            NBitsGenerator.print_hex(msg + " (Big Endian)", data[::-1])

    def generate(self, value: Optional[int] = None) -> bytes:
        """
        Generate n bits data and print its hexadecimal and binary representations.
        """
        gen_bytes = None
        temp_bytes = None
        n_bits = self.msg_cfg.length
        n_bytes = math.ceil(n_bits / 8)

        if self.msg_cfg.random_flag:
            temp_bytes = randbits(n_bits)
        else:
            if value is None:
                raise ValueError("Value must be provided when random_flag is False.")
            temp_bytes = value
        assert temp_bytes is not None, "Value must be provided when random_flag is False."

        gen_bytes = temp_bytes.to_bytes(n_bytes, byteorder=self.hash_cfg.constants.byteorder)
        assert gen_bytes is not None, "Generated bytes is None."
        assert len(gen_bytes) == n_bytes, \
            "Generated bytes length does not match expected byte length."

        if self.runtime_config.main.verbose_flag:
            print(f"Generated {self.msg_cfg.length}-bit random data.")
            self.print_bin_in_big_endian("Data in Binary", gen_bytes,
                                        endian=self.hash_cfg.constants.byteorder)

            print(f"Binary length in Bytes: \n{len(gen_bytes)}\n")
            self.print_hex_in_big_endian(f"Data in Hexadecimal (len: {len(gen_bytes)}bytes)",
                                        gen_bytes, endian=self.hash_cfg.constants.byteorder)

        return gen_bytes

    def main(self, value: Optional[int] = None) -> bytes:
        """
        Main function to generate n bits data.
        """
        msg = None
        perf_timer_start = Logs.perftimer_start()
        msg = self.generate(value)
        perf_timer_end = Logs.perftimer_end(perf_timer_start)

        assert msg is not None, "Message generation failed."
        filename = f"_{self.msg_cfg.length}_bits_{self.gen_start_time[:19]}.bin"
        if self.msg_cfg.random_flag:
            filename = "random" + filename
        else:
            filename = "fixed" + filename
        self.io_controller.file_writer(filename,
                                    msg,
                                    length=self.msg_cfg.length,
                                    timestamp=self.gen_start_time,
                                    elapsed_time=perf_timer_end,
                                    byteorder=self.hash_cfg.constants.byteorder)
        return msg
